version: '2'

services:

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      #      - ~/docker/volumes/mongo:/data/data
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js
