apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: lrs-lost-reports-proto
  labels:
    strimzi.io/cluster: "kafka-cluster"
spec:
  partitions: 3
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: tms-text-messages-proto
  labels:
    strimzi.io/cluster: "kafka-cluster"
spec:
  partitions: 3
  replicas: 1