---
apiVersion: v1
kind: Service
metadata:
  name: lost-report-service
  labels:
    app: lrs
  annotations:
    cloud.google.com/backend-config: |
      {
        "ports": {
          "8080": "lrs-backend",
          "8081": "lrs-backend"
        }
      }
spec:
  type: NodePort
  ports:
    - name: main
      nodePort: 30080
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: management
      nodePort: 30081
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: lrs
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: lrs-backend
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 15
    port: 8081
    type: HTTP
    requestPath: /actuator/health
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lost-report-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lrs
  template:
    metadata:
      labels:
        app: lrs
    spec:
      containers:
        - name: lrs-ctr
          image: registry.gitlab.com/reliable-and-scalable-biskup/lost-report-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 3
      imagePullSecrets:
        - name: regcred
