---
apiVersion: v1
kind: Service
metadata:
  name: text-message-service
  labels:
    app: tms
  annotations:
    cloud.google.com/backend-config: |
      {
        "ports": {
          "7070": "tms-backend",
          "7071": "tms-backend"
        }
      }
spec:
  type: NodePort
  ports:
    - name: main
      nodePort: 30070
      port: 7070
      protocol: TCP
      targetPort: 7070
    - name: management
      nodePort: 30071
      port: 7071
      protocol: TCP
      targetPort: 7071
  selector:
    app: tms
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: tms-backend
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 15
    port: 7071
    type: HTTP
    requestPath: /actuator/health
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-message-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tms
  template:
    metadata:
      labels:
        app: tms
    spec:
      containers:
        - name: tms-ctr
          image: registry.gitlab.com/reliable-and-scalable-biskup/text-message-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
            - containerPort: 7071
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 7071
            initialDelaySeconds: 10
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 7071
            initialDelaySeconds: 10
            periodSeconds: 3
      imagePullSecrets:
        - name: regcred
